name: flutter_support_tickets
description: Local fallback support tickets package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  crypto: ^3.0.3
